//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWebsiteProjectCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message()
        {
            this.message_info = new HashSet<message_info>();
        }
    
        public System.Guid message_id { get; set; }
        public Nullable<System.Guid> user_1 { get; set; }
        public Nullable<System.Guid> user_2 { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message_info> message_info { get; set; }
    }
}
